---

- name: Fetch OS updates
  shell: freebsd-update fetch

- name: Install OS updates
  shell: freebsd-update install
  register: update
  failed_when: update.rc > 2

- name: Check freebsd-version
  shell: freebsd-version
  register: freebsd_version

- name: Check uname -r
  shell: uname -r
  register: uname

- name: Install FreeBSD package and security updates
  shell: pkg update && pkg upgrade -y

- name: Reboot
  reboot:
  when: uname.stdout != freebsd_version.stdout

