---

- name: Install/upgrade OS packages
  shell: pkg install -y bash curl git gmake patch rsync sudo zstd pkgconf sqlite3 libedit capnproto gmp libev graphviz
  become: yes

- name: Remove ~/opam
  file:
    path: "{{ ansible_env.HOME }}/opam"
    state: absent

- name: Download the source from GitHub
  git:
    repo: https://github.com/ocaml/opam
    dest: "{{ ansible_env.HOME }}/opam"
    force: yes
    version: "2.1"

- name: Build opam
  shell: gmake CONFIGURE_ARGS=--with-0install-solver cold && sudo cp -p opam /usr/local/bin/opam
  args:
    chdir: "{{ ansible_env.HOME }}/opam"

