---

- set_fact:
    base_image: "freebsd-ocaml-{{ version.split('.')[:2] | join('.') }}"
  when: version != "busybox"

- set_fact:
    base_image: "busybox"
  when: version == "busybox"

- name: Check for existing base image {{ zfs_pool }}/base-image/{{ base_image }}
  shell: zfs list -H -o name {{ zfs_pool }}/base-image/{{ base_image }}
  register: zfs_check
  failed_when: zfs_check.rc > 1

- name: Delete existing base image {{ zfs_pool }}/base-image/{{ base_image }}
  shell: zfs destroy -R -r {{ zfs_pool }}/base-image/{{ base_image }}
  when: zfs_check.rc == 0

- name: Create target for base image {{ zfs_pool }}/base-image/{{ base_image }}/rootfs
  shell: zfs create -p {{ zfs_pool }}/base-image/{{ base_image }}/rootfs

- name: Copy the bsdinstall answer script
  copy:
    src: jail
    dest: jail

- name: Install FreeBSD in jail /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs
  shell: bsdinstall -D jail.log script jail /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs

- name: Fetch and install OS updates for the jail
  shell: freebsd-update -b /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs fetch install

- name: Upgrade pkg
  shell: pkg --chroot /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs install -y pkg

- name: Upgrade pkg packages
  shell: pkg --chroot /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs upgrade -f -y

- name: Create OS setup script /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs/root/freebsd.sh
  copy:
    dest: "/{{ zfs_pool }}/base-image/{{ base_image }}/rootfs/root/freebsd.sh"
    mode: u+rwx,g+rx,o+rx
    content: |
      #!/bin/sh
      pw groupadd opam -g 1000
      pw useradd -m -n opam -g opam -u 1000 -h - -c {{ user_name }}
      pkg install -y sudo gmake git patch rsync bash zstd pkgconf
      echo "{{ user_name }} ALL=(ALL:ALL) NOPASSWD: ALL" > "/usr/local/etc/sudoers.d/{{ user_name }}"

- name: Run script in jail /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs
  shell: jail -c name=base-image path=/{{ zfs_pool }}/base-image/{{ base_image }}/rootfs host=inherit ip6=inherit ip4=inherit mount.devfs command=/root/freebsd.sh

- name: Unmount devfs
  shell: umount -f /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs/dev

- name: Create setup script
  copy:
    dest: "/{{ zfs_pool }}/base-image/{{ base_image }}/rootfs/home/{{ user_name }}/freebsd-ocaml.sh"
    mode: u+rwx,g+rx,o+rx
    content: |
      #!/bin/sh
      cd /home/opam
      touch .hushlogin
      sed -i "" 's/^[^#]*fortune/# &/' .profile .login
      echo "OPAMCONFIRMLEVEL=unsafe-yes; export OPAMCONFIRMLEVEL" >> .profile
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git clone https://github.com/ocaml/opam /home/opam/opam && cd /home/opam/opam && cp -P -R -p . ../opam-sources && git checkout 62ad0c21768e28532466572dbaa066913a6c050d && git remote add mtelvers https://github.com/mtelvers/opam && git fetch mtelvers && git cherry-pick bfa86fcc5187bf71080d5f934ff147cdbb64a9e1 && env MAKE='gmake -j' shell/bootstrap-ocaml.sh && gmake -C src_ext cache-archives
      cd /home/opam/opam-sources && cp -P -R -p . ../opam-build-2.0 && cd ../opam-build-2.0 && git checkout 2.0 && ln -s ../opam/src_ext/archives src_ext/archives && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" ./configure --enable-cold-check && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" gmake lib-ext all && mkdir -p /usr/local/bin && sudo cp /home/opam/opam-build-2.0/opam /usr/local/bin/opam-2.0 && sudo chmod a+x /usr/local/bin/opam-2.0 && rm -rf /home/opam/opam-build-2.0
      cd /home/opam/opam-sources && cp -P -R -p . ../opam-build-2.1 && cd ../opam-build-2.1 && git checkout 2.1 && ln -s ../opam/src_ext/archives src_ext/archives && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" ./configure --enable-cold-check --with-0install-solver && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" gmake lib-ext all && mkdir -p /usr/local/bin && sudo cp /home/opam/opam-build-2.1/opam /usr/local/bin/opam-2.1 && sudo chmod a+x /usr/local/bin/opam-2.1 && rm -rf /home/opam/opam-build-2.1
      cd /home/opam/opam-sources && cp -P -R -p . ../opam-build-master && cd ../opam-build-master && git checkout master && ln -s ../opam/src_ext/archives src_ext/archives && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" ./configure --enable-cold-check --with-0install-solver --with-vendored-deps && env PATH="/home/opam/opam/bootstrap/ocaml/bin:$PATH" gmake lib-ext all && mkdir -p /usr/local/bin && sudo cp /home/opam/opam-build-master/opam /usr/local/bin/opam-dev && sudo chmod a+x /usr/local/bin/opam-master && rm -rf /home/opam/opam-build-master
      sudo ln /usr/local/bin/opam-2.1 /usr/local/bin/opam
      cd /home/opam
      git clone https://github.com/ocaml/opam-repository.git
      opam init -k git -a ./opam-repository -c {{ version }} -y
  when: version != "busybox"

- name: Run freebsd-ocaml.sh script in jail /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs as user {{ user_name }} for {{ version }}
  shell: jail -c name=base-image path=/{{ zfs_pool }}/base-image/{{ base_image }}/rootfs host=inherit ip6=inherit ip4=inherit mount.devfs exec.jail_user=opam command=/home/opam/freebsd-ocaml.sh
  when: version != "busybox"

- name: Unmount devfs
  shell: umount -f /{{ zfs_pool }}/base-image/{{ base_image }}/rootfs/dev
  when: version != "busybox"

- name: Create a snapshot of the base image
  shell: zfs snapshot -r {{ zfs_pool }}/base-image/{{ base_image }}@snap

- name: Clone if it is the default
  when: default == true
  shell: |
    zfs clone -p {{ zfs_pool }}/base-image/{{ base_image }}@snap {{ zfs_pool }}/base-image/freebsd
    zfs clone -p {{ zfs_pool }}/base-image/{{ base_image }}/rootfs@snap {{ zfs_pool }}/base-image/freebsd/rootfs
    zfs snapshot -r {{ zfs_pool }}/base-image/freebsd@snap

